#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/

# $LOCKSCREEN = hyprlock # preferred LOCKSCREEN e.g swaylock
$LOCKSCREEN = lockscreen.sh # Calls $LOCKSCREEN set from hyprland
$LOCK_CMD = hyde-shell lockscreen.sh # Calls $LOCKSCREEN default is hyprlock
$UNLOCK_CMD = sh -c 'sleep 3 && pkill -9 $(hyde-shell lockscreen --get)' # kills the lockscreen after 3 seconds for cleanup

general {
    lock_cmd = $LOCKSCREEN # Registers the lockscreen command to dbus so it can be invoked by `loginctl lock-session`
    # unlock_cmd = #notify-send "unlock!"      # Command to run on unlock (optional)
    before_sleep_cmd = loginctl lock-session    # Locks before sleep
    # after_sleep_cmd = # notify-send "Awake!"  # Command after waking up (optional)
    ignore_dbus_inhibit = false             # Ignore dbus idle-inhibit requests (false = respect them)
    ignore_systemd_inhibit = false          # Ignore systemd-inhibit --what=idle (false = respect them)
}

# Dims the display
# listener {
#     timeout = 120
#     on-timeout = { brightnessctl -s && brightnessctl s 50% ;}
#     on-resume = brightnessctl -r
# }

# Lock it first before dpms off so that screen won't show for a moment after wake up.
# listener {
#     timeout = 120
#     on-timeout = $LOCKSCREEN
# }

# DPMS off
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off #do not turn off display while media is playing
    on-resume = { hyprctl dispatch dpms on && dunst ;}
}

# Suspend
# listener {
#     timeout = 500
#    on-timeout = systemctl suspend
# }


# hyprlang noerror true
# Source anything  from this path if you want to add your own listener
# source command actually do not exist yet
source = ~/.config/hypridle/*
# hyprlang noerror false
