#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/


<<<<<<< HEAD
source = $HOME/.local/share/hyde/hyprland.conf # HyDE's core configuration // DO NOT TOUCH!!! ( ｡ •̀ ᴖ •́ ｡)
=======
# ------------------------------------------------------
#TODO Please remove this block if you are sure $HYPRLAND_CONFIG is set
#? This is only use for fallback
source = $HOME/.local/share/hyde/hyprland.conf # Fallback when HYPRLAND_CONFIG is not set
# -------------------------------------------------------

#? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

>>>>>>> c1c172bf2fc07c7f64046a8438152bc2d948a35b
source = ./keybindings.conf # Keyboard shortcuts
source = ./windowrules.conf # Window rules
source = ./monitors.conf # Monitor configuration
source = ./userprefs.conf # Your hyprland configuration // Edit this file to change your Hyprland configuration
source = ./workflows.conf # workflows configuration overrides everything

# // ██████╗░░█████╗░  ███╗░░██╗░█████╗░████████╗  ███████╗██████╗░██╗████████╗
# // ██╔══██╗██╔══██╗  ████╗░██║██╔══██╗╚══██╔══╝  ██╔════╝██╔══██╗██║╚══██╔══╝
# // ██║░░██║██║░░██║  ██╔██╗██║██║░░██║░░░██║░░░  █████╗░░██║░░██║██║░░░██║░░░
# // ██║░░██║██║░░██║  ██║╚████║██║░░██║░░░██║░░░  ██╔══╝░░██║░░██║██║░░░██║░░░
# // ██████╔╝╚█████╔╝  ██║░╚███║╚█████╔╝░░░██║░░░  ███████╗██████╔╝██║░░░██║░░░
# // ╚═════╝░░╚════╝░  ╚═╝░░╚══╝░╚════╝░░░░╚═╝░░░  ╚══════╝╚═════╝░╚═╝░░░╚═╝░░░
